[2024-10-14T07:00:03.789+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:00:03.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:00:03.829+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:00:03.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:00:04.187+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:00:04.113+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:00:04.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:00:05.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 1.574 seconds
[2024-10-14T07:00:47.013+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:00:47.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:00:47.035+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:00:47.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:00:47.219+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:00:47.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:00:47.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:00:47.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.323 seconds
[2024-10-14T07:01:17.737+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:01:17.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:01:17.808+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:01:17.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:01:18.019+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:01:17.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:01:18.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:01:18.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.430 seconds
[2024-10-14T07:01:48.249+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:01:48.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:01:48.256+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:01:48.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:01:48.286+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:01:48.279+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:01:48.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:01:48.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.078 seconds
[2024-10-14T07:02:19.187+0000] {processor.py:186} INFO - Started process (PID=328) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:02:19.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:02:19.195+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:02:19.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:02:19.227+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:02:19.220+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:02:19.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:02:19.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.087 seconds
[2024-10-14T07:02:49.418+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:02:49.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:02:49.422+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:02:49.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:02:49.453+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:02:49.445+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:02:49.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:02:49.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.079 seconds
[2024-10-14T07:03:19.931+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:03:19.932+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:03:19.936+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:03:19.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:03:19.992+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:03:19.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:03:19.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:03:20.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.114 seconds
[2024-10-14T07:03:50.938+0000] {processor.py:186} INFO - Started process (PID=515) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:03:50.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:03:50.946+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:03:50.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:03:50.986+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:03:50.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:03:50.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:03:51.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.093 seconds
[2024-10-14T07:04:21.482+0000] {processor.py:186} INFO - Started process (PID=577) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:04:21.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:04:21.493+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:04:21.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:04:21.528+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:04:21.519+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:04:21.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:04:21.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.107 seconds
[2024-10-14T07:04:51.861+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:04:51.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:04:51.874+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:04:51.872+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:04:51.922+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:04:51.912+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:04:51.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:04:51.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.127 seconds
[2024-10-14T07:05:22.528+0000] {processor.py:186} INFO - Started process (PID=700) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:05:22.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:05:22.535+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:05:22.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:05:22.564+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:05:22.556+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:05:22.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:05:22.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.095 seconds
[2024-10-14T07:05:53.590+0000] {processor.py:186} INFO - Started process (PID=763) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:05:53.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:05:53.594+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:05:53.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:05:53.623+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:05:53.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:05:53.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:05:53.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.064 seconds
[2024-10-14T07:06:24.055+0000] {processor.py:186} INFO - Started process (PID=826) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:06:24.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:06:24.063+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:06:24.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:06:24.117+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:06:24.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:06:24.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:06:24.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.117 seconds
[2024-10-14T07:06:54.409+0000] {processor.py:186} INFO - Started process (PID=889) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:06:54.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:06:54.433+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:06:54.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:06:54.628+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:06:54.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:06:54.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:06:54.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.308 seconds
[2024-10-14T07:07:24.820+0000] {processor.py:186} INFO - Started process (PID=953) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:07:24.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:07:24.824+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:07:24.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:07:24.854+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:07:24.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:07:24.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:07:24.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.066 seconds
[2024-10-14T07:07:55.268+0000] {processor.py:186} INFO - Started process (PID=1015) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:07:55.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:07:55.273+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:07:55.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:07:55.316+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:07:55.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:07:55.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:07:55.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.085 seconds
[2024-10-14T07:08:25.985+0000] {processor.py:186} INFO - Started process (PID=1078) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:08:25.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:08:25.991+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:08:25.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:08:26.022+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:08:26.016+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:08:26.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:08:26.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.066 seconds
[2024-10-14T07:08:56.372+0000] {processor.py:186} INFO - Started process (PID=1141) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:08:56.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:08:56.375+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:08:56.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:08:56.406+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:08:56.399+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:08:56.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:08:56.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.073 seconds
[2024-10-14T07:09:26.608+0000] {processor.py:186} INFO - Started process (PID=1204) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:09:26.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:09:26.616+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:09:26.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:09:26.651+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:09:26.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:09:26.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:09:26.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.105 seconds
[2024-10-14T07:09:56.893+0000] {processor.py:186} INFO - Started process (PID=1267) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:09:56.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:09:56.903+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:09:56.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:09:56.995+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:09:56.953+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:09:57.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:09:57.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.192 seconds
[2024-10-14T07:10:27.160+0000] {processor.py:186} INFO - Started process (PID=1330) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:10:27.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:10:27.167+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:10:27.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:10:27.205+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:10:27.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:10:27.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:10:27.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.074 seconds
[2024-10-14T07:11:10.643+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:11:10.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:11:10.689+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:11:10.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:11:10.749+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:11:10.724+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:11:10.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:11:10.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.260 seconds
[2024-10-14T07:11:41.269+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:11:41.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:11:41.276+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:11:41.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:11:41.313+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:11:41.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:11:41.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:11:41.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.083 seconds
[2024-10-14T07:12:12.084+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:12:12.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:12:12.093+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:12:12.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:12:12.138+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:12:12.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:12:12.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:12:12.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.103 seconds
[2024-10-14T07:12:42.707+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:12:42.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:12:42.712+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:12:42.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:12:42.750+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:12:42.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:12:42.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:12:42.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.073 seconds
[2024-10-14T07:13:13.642+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:13:13.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:13:13.647+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:13:13.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:13:13.683+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:13:13.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:13:13.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:13:13.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.087 seconds
[2024-10-14T07:13:44.071+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:13:44.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:13:44.079+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:13:44.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:13:44.115+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:13:44.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:13:44.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:13:44.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.101 seconds
[2024-10-14T07:14:14.907+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:14:14.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:14:14.913+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:14:14.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:14:14.944+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:14:14.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:14:14.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:14:14.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.073 seconds
[2024-10-14T07:14:45.868+0000] {processor.py:186} INFO - Started process (PID=512) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:14:45.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:14:45.878+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:14:45.877+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:14:45.919+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:14:45.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:14:45.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:14:45.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.095 seconds
[2024-10-14T07:15:16.446+0000] {processor.py:186} INFO - Started process (PID=575) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:15:16.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:15:16.453+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:15:16.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:15:16.495+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:15:16.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:15:16.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:15:16.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.097 seconds
[2024-10-14T07:15:47.193+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:15:47.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:15:47.201+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:15:47.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:15:47.248+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:15:47.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:15:47.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:15:47.289+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.108 seconds
[2024-10-14T07:16:18.053+0000] {processor.py:186} INFO - Started process (PID=701) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:16:18.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:16:18.059+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:16:18.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:16:18.096+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:16:18.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:16:18.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:16:18.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.079 seconds
[2024-10-14T07:16:48.318+0000] {processor.py:186} INFO - Started process (PID=764) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:16:48.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:16:48.322+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:16:48.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:16:48.366+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:16:48.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:16:48.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:16:48.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.081 seconds
[2024-10-14T07:17:19.026+0000] {processor.py:186} INFO - Started process (PID=827) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:17:19.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:17:19.033+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:17:19.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:17:19.107+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:17:19.091+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:17:19.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:17:19.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.119 seconds
[2024-10-14T07:17:49.327+0000] {processor.py:186} INFO - Started process (PID=891) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:17:49.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:17:49.332+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:17:49.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:17:49.364+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:17:49.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:17:49.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:17:49.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.080 seconds
[2024-10-14T07:18:20.279+0000] {processor.py:186} INFO - Started process (PID=954) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:18:20.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:18:20.285+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:18:20.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:18:20.320+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:18:20.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:18:20.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:18:20.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.095 seconds
[2024-10-14T07:18:51.089+0000] {processor.py:186} INFO - Started process (PID=1017) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:18:51.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:18:51.094+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:18:51.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:18:51.146+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:18:51.135+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:18:51.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:18:51.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.096 seconds
[2024-10-14T07:19:21.993+0000] {processor.py:186} INFO - Started process (PID=1080) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:19:21.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:19:21.998+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:19:21.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:19:22.035+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:19:22.026+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:19:22.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:19:22.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.072 seconds
[2024-10-14T07:19:52.242+0000] {processor.py:186} INFO - Started process (PID=1143) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:19:52.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:19:52.247+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:19:52.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:19:52.291+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:19:52.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:19:52.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:19:52.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.093 seconds
[2024-10-14T07:20:22.555+0000] {processor.py:186} INFO - Started process (PID=1207) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:20:22.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:20:22.560+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:20:22.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:20:22.596+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:20:22.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:20:22.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:20:22.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.068 seconds
[2024-10-14T07:20:53.439+0000] {processor.py:186} INFO - Started process (PID=1270) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:20:53.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:20:53.444+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:20:53.444+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:20:53.484+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:20:53.475+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:20:53.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:20:53.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.082 seconds
[2024-10-14T07:21:24.256+0000] {processor.py:186} INFO - Started process (PID=1333) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:21:24.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:21:24.260+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:21:24.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:21:24.316+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:21:24.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:21:24.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:21:24.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.100 seconds
[2024-10-14T07:21:54.812+0000] {processor.py:186} INFO - Started process (PID=1396) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:21:54.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:21:54.817+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:21:54.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:21:54.846+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:21:54.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:21:54.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:21:54.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.065 seconds
[2024-10-14T07:22:25.863+0000] {processor.py:186} INFO - Started process (PID=1459) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:22:25.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:22:25.868+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:22:25.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:22:25.910+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:22:25.902+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:22:25.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:22:25.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.080 seconds
[2024-10-14T07:22:56.607+0000] {processor.py:186} INFO - Started process (PID=1522) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:22:56.609+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:22:56.613+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:22:56.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:22:56.648+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:22:56.638+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), 'scrapers\stock_data_scraper.py'))
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2024-10-14T07:22:56.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:22:56.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.083 seconds
[2024-10-14T07:23:06.190+0000] {processor.py:186} INFO - Started process (PID=1557) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:23:06.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:23:06.199+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:23:06.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:23:06.247+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:23:06.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:23:06.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:23:06.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.098 seconds
[2024-10-14T07:23:36.386+0000] {processor.py:186} INFO - Started process (PID=1614) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:23:36.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:23:36.392+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:23:36.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:23:36.428+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:23:36.422+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:23:36.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:23:36.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.072 seconds
[2024-10-14T07:24:07.478+0000] {processor.py:186} INFO - Started process (PID=1677) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:24:07.480+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:24:07.485+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:24:07.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:24:07.527+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:24:07.519+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:24:07.530+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:24:07.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.082 seconds
[2024-10-14T07:24:37.741+0000] {processor.py:186} INFO - Started process (PID=1740) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:24:37.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:24:37.746+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:24:37.746+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:24:37.785+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:24:37.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:24:37.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:24:37.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.077 seconds
[2024-10-14T07:26:27.225+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:26:27.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:26:27.232+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:26:27.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:26:27.271+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:26:27.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:26:27.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:26:27.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.113 seconds
[2024-10-14T07:26:57.712+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:26:57.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:26:57.718+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:26:57.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:26:57.754+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:26:57.746+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:26:57.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:26:57.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.080 seconds
[2024-10-14T07:27:28.073+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:27:28.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:27:28.079+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:27:28.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:27:28.123+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:27:28.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:27:28.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:27:28.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.080 seconds
[2024-10-14T07:27:59.060+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:27:59.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:27:59.075+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:27:59.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:27:59.110+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:27:59.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:27:59.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:27:59.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.085 seconds
[2024-10-14T07:28:29.787+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:28:29.789+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:28:29.792+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:28:29.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:28:29.834+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:28:29.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:28:29.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:28:29.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.084 seconds
[2024-10-14T07:29:00.205+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:29:00.206+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:29:00.210+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:29:00.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:29:00.250+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:29:00.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:29:00.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:29:00.277+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.078 seconds
[2024-10-14T07:29:42.441+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:29:42.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:29:42.451+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:29:42.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:29:42.482+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:29:42.475+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:29:42.485+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:29:42.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.096 seconds
[2024-10-14T07:30:12.757+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:30:12.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:30:12.763+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:30:12.762+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:30:12.805+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:30:12.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:30:12.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:30:12.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.082 seconds
[2024-10-14T07:30:43.756+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:30:43.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:30:43.761+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:30:43.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:30:43.793+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:30:43.788+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:30:43.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:30:43.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.067 seconds
[2024-10-14T07:31:14.515+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:31:14.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:31:14.521+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:31:14.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:31:14.558+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:31:14.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:31:14.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:31:14.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.087 seconds
[2024-10-14T07:31:45.274+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:31:45.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:31:45.278+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:31:45.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:31:45.321+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:31:45.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:31:45.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:31:45.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.085 seconds
[2024-10-14T07:32:15.629+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:32:15.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:32:15.634+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:32:15.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:32:15.667+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:32:15.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:32:15.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:32:15.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.074 seconds
[2024-10-14T07:32:46.519+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:32:46.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:32:46.523+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:32:46.523+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:32:46.549+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:32:46.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:32:46.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:32:46.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.065 seconds
[2024-10-14T07:33:17.075+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:33:17.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:33:17.081+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:33:17.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:33:17.119+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:33:17.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:33:17.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:33:17.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.072 seconds
[2024-10-14T07:33:47.888+0000] {processor.py:186} INFO - Started process (PID=577) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:33:47.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:33:47.892+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:33:47.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:33:47.928+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:33:47.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 10, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:33:47.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:33:47.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.068 seconds
[2024-10-14T07:33:58.682+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:33:58.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:33:58.688+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:33:58.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:33:58.742+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:33:58.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:33:58.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:33:58.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.109 seconds
[2024-10-14T07:34:10.836+0000] {processor.py:186} INFO - Started process (PID=635) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:34:10.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:34:10.840+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:34:10.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:34:10.899+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:34:10.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:34:10.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:34:10.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.094 seconds
[2024-10-14T07:34:41.665+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:34:41.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:34:41.669+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:34:41.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:34:41.715+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:34:41.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:34:41.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:34:41.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.079 seconds
[2024-10-14T07:35:09.208+0000] {processor.py:186} INFO - Started process (PID=761) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:35:09.209+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:35:09.213+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:35:09.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:35:09.255+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:35:09.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:35:09.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:35:09.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.081 seconds
[2024-10-14T07:36:42.396+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:36:42.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:36:42.404+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:36:42.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:36:42.440+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:36:42.432+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:36:42.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:36:42.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.106 seconds
[2024-10-14T07:37:13.125+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:37:13.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:37:13.128+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:37:13.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:37:13.159+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:37:13.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:37:13.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:37:13.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.063 seconds
[2024-10-14T07:37:44.170+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:37:44.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:37:44.178+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:37:44.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:37:44.218+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:37:44.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:37:44.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:37:44.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.082 seconds
[2024-10-14T07:38:15.016+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:38:15.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:38:15.044+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:38:15.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:38:15.160+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:38:15.144+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:38:15.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:38:15.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.219 seconds
[2024-10-14T07:38:45.853+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:38:45.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:38:45.860+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:38:45.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:38:45.915+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:38:45.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:38:45.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:38:45.949+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.105 seconds
[2024-10-14T07:39:16.604+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:39:16.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:39:16.609+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:39:16.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:39:16.652+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:39:16.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:39:16.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:39:16.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.107 seconds
[2024-10-14T07:39:46.858+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:39:46.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:39:46.864+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:39:46.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:39:46.910+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:39:46.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:39:46.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:39:46.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.089 seconds
[2024-10-14T07:40:17.895+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:40:17.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:40:17.900+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:40:17.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:40:17.942+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:40:17.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:40:17.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:40:17.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.074 seconds
[2024-10-14T07:40:48.451+0000] {processor.py:186} INFO - Started process (PID=577) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:40:48.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:40:48.455+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:40:48.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:40:48.486+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:40:48.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:40:48.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:40:48.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.064 seconds
[2024-10-14T07:41:19.131+0000] {processor.py:186} INFO - Started process (PID=641) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:41:19.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:41:19.134+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:41:19.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:41:19.160+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:41:19.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:41:19.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:41:19.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.055 seconds
[2024-10-14T07:41:49.843+0000] {processor.py:186} INFO - Started process (PID=704) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:41:49.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:41:49.848+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:41:49.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:41:49.896+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:41:49.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:41:49.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:41:49.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.082 seconds
[2024-10-14T07:42:20.785+0000] {processor.py:186} INFO - Started process (PID=766) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:42:20.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:42:20.789+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:42:20.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:42:20.827+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:42:20.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:42:20.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:42:20.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.072 seconds
[2024-10-14T07:42:51.545+0000] {processor.py:186} INFO - Started process (PID=829) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:42:51.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:42:51.550+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:42:51.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:42:51.594+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:42:51.585+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:42:51.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:42:51.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.080 seconds
[2024-10-14T07:43:22.425+0000] {processor.py:186} INFO - Started process (PID=892) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:43:22.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:43:22.429+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:43:22.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:43:22.471+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:43:22.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:43:22.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:43:22.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.078 seconds
[2024-10-14T07:43:52.800+0000] {processor.py:186} INFO - Started process (PID=955) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:43:52.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:43:52.806+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:43:52.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:43:52.845+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:43:52.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:43:52.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:43:52.875+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.082 seconds
[2024-10-14T07:44:23.720+0000] {processor.py:186} INFO - Started process (PID=1018) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:44:23.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:44:23.724+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:44:23.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:44:23.763+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:44:23.755+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:44:23.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:44:23.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.075 seconds
[2024-10-14T07:44:54.328+0000] {processor.py:186} INFO - Started process (PID=1081) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:44:54.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:44:54.335+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:44:54.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:44:54.370+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:44:54.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:44:54.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:44:54.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.072 seconds
[2024-10-14T07:45:24.887+0000] {processor.py:186} INFO - Started process (PID=1144) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:45:24.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:45:24.893+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:45:24.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:45:24.941+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:45:24.931+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:45:24.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:45:24.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.095 seconds
[2024-10-14T07:45:55.663+0000] {processor.py:186} INFO - Started process (PID=1207) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:45:55.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:45:55.672+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:45:55.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:45:55.698+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:45:55.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:45:55.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:45:55.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.070 seconds
[2024-10-14T07:46:26.071+0000] {processor.py:186} INFO - Started process (PID=1270) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:46:26.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:46:26.076+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:46:26.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:46:26.104+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:46:26.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:46:26.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:46:26.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.068 seconds
[2024-10-14T07:46:56.950+0000] {processor.py:186} INFO - Started process (PID=1333) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:46:56.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:46:56.956+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:46:56.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:46:56.983+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:46:56.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:46:56.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:46:57.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.077 seconds
[2024-10-14T07:47:27.537+0000] {processor.py:186} INFO - Started process (PID=1396) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:47:27.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:47:27.545+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:47:27.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:47:27.860+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:47:27.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:47:27.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:47:27.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.358 seconds
[2024-10-14T07:47:58.742+0000] {processor.py:186} INFO - Started process (PID=1459) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:47:58.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:47:58.747+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:47:58.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:47:58.789+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:47:58.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:47:58.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:47:58.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.087 seconds
[2024-10-14T07:48:29.737+0000] {processor.py:186} INFO - Started process (PID=1522) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:48:29.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:48:29.746+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:48:29.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:48:29.794+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:48:29.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:48:29.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:48:29.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.094 seconds
[2024-10-14T07:49:00.445+0000] {processor.py:186} INFO - Started process (PID=1585) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:49:00.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:49:00.452+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:49:00.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:49:00.489+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:49:00.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:49:00.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:49:00.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.081 seconds
[2024-10-14T07:49:30.735+0000] {processor.py:186} INFO - Started process (PID=1647) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:49:30.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:49:30.741+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:49:30.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:49:30.791+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:49:30.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:49:30.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:49:30.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.096 seconds
[2024-10-14T07:50:01.397+0000] {processor.py:186} INFO - Started process (PID=1711) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:50:01.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:50:01.403+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:50:01.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:50:01.445+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:50:01.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:50:01.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:50:01.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.081 seconds
[2024-10-14T07:50:31.781+0000] {processor.py:186} INFO - Started process (PID=1774) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:50:31.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:50:31.787+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:50:31.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:50:31.826+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:50:31.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 8, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:50:31.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:50:31.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.090 seconds
[2024-10-14T07:50:34.151+0000] {processor.py:186} INFO - Started process (PID=1789) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:50:34.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:50:34.155+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:50:34.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:50:34.206+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:50:34.198+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:50:34.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:50:34.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.083 seconds
[2024-10-14T07:51:04.592+0000] {processor.py:186} INFO - Started process (PID=1851) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:51:04.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:51:04.596+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:51:04.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:51:04.628+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:51:04.621+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:51:04.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:51:04.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.071 seconds
[2024-10-14T07:51:35.219+0000] {processor.py:186} INFO - Started process (PID=1914) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:51:35.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:51:35.226+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:51:35.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:51:35.257+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:51:35.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:51:35.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:51:35.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.085 seconds
[2024-10-14T07:52:05.751+0000] {processor.py:186} INFO - Started process (PID=1976) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:52:05.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:52:05.761+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:52:05.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:52:05.801+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:52:05.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:52:05.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:52:05.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.098 seconds
[2024-10-14T07:52:36.257+0000] {processor.py:186} INFO - Started process (PID=2039) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:52:36.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:52:36.264+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:52:36.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:52:36.298+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:52:36.292+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:52:36.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:52:36.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.084 seconds
[2024-10-14T07:53:06.434+0000] {processor.py:186} INFO - Started process (PID=2098) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:53:06.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:53:06.444+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:53:06.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:53:06.489+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:53:06.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:53:06.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:53:06.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.116 seconds
[2024-10-14T07:53:37.040+0000] {processor.py:186} INFO - Started process (PID=2160) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:53:37.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:53:37.064+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:53:37.063+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:53:37.119+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:53:37.113+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:53:37.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:53:37.143+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.111 seconds
[2024-10-14T07:54:07.392+0000] {processor.py:186} INFO - Started process (PID=2216) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:54:07.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:54:07.398+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:54:07.398+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:54:07.457+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:54:07.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:54:07.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:54:07.490+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.106 seconds
[2024-10-14T07:54:25.251+0000] {processor.py:186} INFO - Started process (PID=2279) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:54:25.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:54:25.257+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:54:25.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:54:25.312+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:54:25.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:54:25.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:54:25.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.108 seconds
[2024-10-14T07:56:26.639+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:56:26.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:56:26.648+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:56:26.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:56:26.698+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:56:26.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:56:26.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:56:26.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.143 seconds
[2024-10-14T07:56:57.784+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:56:57.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:56:57.787+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:56:57.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:56:57.817+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:56:57.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:56:57.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:56:57.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.087 seconds
[2024-10-14T07:57:28.259+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:57:28.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:57:28.267+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:57:28.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:57:28.306+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:57:28.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:57:28.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:57:28.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.093 seconds
[2024-10-14T07:57:58.817+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:57:58.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:57:58.823+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:57:58.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:57:58.859+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:57:58.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:57:58.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:57:58.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.072 seconds
[2024-10-14T07:58:29.429+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:58:29.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:58:29.435+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:58:29.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:58:29.475+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:58:29.467+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 14, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:58:29.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:58:29.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.088 seconds
[2024-10-14T07:58:49.995+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:58:49.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:58:50.004+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:58:50.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:58:50.050+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:58:50.043+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:58:50.054+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/stock_scraper_dag.py:13 SyntaxWarning: invalid escape sequence '\s'
[2024-10-14T07:58:50.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:58:50.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.110 seconds
[2024-10-14T07:59:51.760+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:59:51.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T07:59:51.776+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:59:51.775+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:59:51.810+0000] {logging_mixin.py:190} INFO - [2024-10-14T07:59:51.803+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T07:59:51.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T07:59:51.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.111 seconds
[2024-10-14T08:00:22.033+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:00:22.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:00:22.045+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:00:22.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:00:22.101+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:00:22.092+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:00:22.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:00:22.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.120 seconds
[2024-10-14T08:00:53.123+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:00:53.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:00:53.129+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:00:53.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:00:53.170+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:00:53.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:00:53.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:00:53.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.082 seconds
[2024-10-14T08:01:23.412+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:01:23.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:01:23.418+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:01:23.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:01:23.457+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:01:23.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:01:23.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:01:23.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.087 seconds
[2024-10-14T08:01:53.413+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:01:53.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:01:53.423+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:01:53.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:01:53.455+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:01:53.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:01:53.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:01:53.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.077 seconds
[2024-10-14T08:04:19.974+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:04:19.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:04:19.982+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:04:19.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:04:20.022+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:04:20.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:04:20.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:04:20.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.104 seconds
[2024-10-14T08:04:50.580+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:04:50.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:04:50.585+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:04:50.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:04:50.621+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:04:50.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:04:50.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:04:50.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.073 seconds
[2024-10-14T08:05:32.199+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:05:32.202+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:05:32.210+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:05:32.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:05:32.250+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:05:32.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:05:32.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:05:32.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.106 seconds
[2024-10-14T08:06:02.698+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:06:02.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:06:02.703+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:06:02.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:06:02.739+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:06:02.737+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:06:02.740+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:06:02.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.070 seconds
[2024-10-14T08:06:33.621+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:06:33.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:06:33.629+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:06:33.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:06:33.670+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:06:33.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:06:33.671+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:06:33.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.074 seconds
[2024-10-14T08:07:04.192+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:07:04.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:07:04.196+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:07:04.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:07:04.229+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:07:04.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:07:04.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:07:04.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.063 seconds
[2024-10-14T08:07:34.575+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:07:34.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:07:34.580+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:07:34.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:07:34.609+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:07:34.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:07:34.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:07:34.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.078 seconds
[2024-10-14T08:08:05.532+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:08:05.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:08:05.535+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:08:05.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:08:05.569+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:08:05.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:08:05.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:08:05.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.065 seconds
[2024-10-14T08:08:36.129+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:08:36.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:08:36.138+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:08:36.137+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:08:36.169+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:08:36.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:08:36.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:08:36.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.078 seconds
[2024-10-14T08:09:06.489+0000] {processor.py:186} INFO - Started process (PID=512) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:09:06.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:09:06.496+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:09:06.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:09:06.530+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:09:06.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:09:06.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:09:06.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.069 seconds
[2024-10-14T08:09:37.353+0000] {processor.py:186} INFO - Started process (PID=575) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:09:37.355+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:09:37.358+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:09:37.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:09:37.411+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:09:37.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:09:37.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:09:37.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.084 seconds
[2024-10-14T08:10:08.420+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:10:08.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:10:08.425+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:10:08.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:10:08.467+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:10:08.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:10:08.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:10:08.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.080 seconds
[2024-10-14T08:10:39.328+0000] {processor.py:186} INFO - Started process (PID=701) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:10:39.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:10:39.335+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:10:39.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:10:39.376+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:10:39.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 13
    sys.path.append('C:\Users\a895279\OneDrive - Eviden\Documents\Portafolio\0_pipeline_essais\3_ONGOING-Stock-Data-scrapt_python-BQ-airflow\scrapers\stock_data_scraper.py')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-10-14T08:10:39.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:10:39.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.077 seconds
[2024-10-14T08:10:45.410+0000] {processor.py:186} INFO - Started process (PID=737) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:10:45.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:10:45.417+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:10:45.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:10:45.467+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:10:45.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:10:45.473+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/stock_scraper_dag.py:13 SyntaxWarning: invalid escape sequence '\s'
[2024-10-14T08:10:45.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:10:45.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.097 seconds
[2024-10-14T08:11:34.396+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:11:34.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:11:34.406+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:11:34.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:11:34.445+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:11:34.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:11:34.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:11:34.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.116 seconds
[2024-10-14T08:12:04.895+0000] {processor.py:186} INFO - Started process (PID=128) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:12:04.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:12:04.904+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:12:04.904+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:12:04.938+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:12:04.933+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:12:04.941+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:12:04.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.082 seconds
[2024-10-14T08:12:35.222+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:12:35.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:12:35.228+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:12:35.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:12:35.264+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:12:35.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:12:35.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:12:35.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.083 seconds
[2024-10-14T08:13:06.307+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:13:06.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:13:06.313+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:13:06.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:13:06.352+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:13:06.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:13:06.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:13:06.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.082 seconds
[2024-10-14T08:13:36.648+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:13:36.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:13:36.653+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:13:36.653+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:13:36.688+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:13:36.681+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:13:36.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:13:36.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.075 seconds
[2024-10-14T08:14:07.618+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:14:07.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:14:07.624+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:14:07.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:14:07.669+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:14:07.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:14:07.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:14:07.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.084 seconds
[2024-10-14T08:14:38.402+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:14:38.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_scraper_dag.py for tasks to queue
[2024-10-14T08:14:38.409+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:14:38.408+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:14:38.451+0000] {logging_mixin.py:190} INFO - [2024-10-14T08:14:38.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_scraper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_scraper_dag.py", line 15, in <module>
    from scrapers.stock_data_scraper import StockDataScraper
ModuleNotFoundError: No module named 'scrapers'
[2024-10-14T08:14:38.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_scraper_dag.py
[2024-10-14T08:14:38.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_scraper_dag.py took 0.086 seconds
